In [1]:
import plotly.express as px
import pandas as pd

In [ ]:
atmospheric_pressure = 760 
freq_hz = 60

def plot_pressure(csv_file, convert_with_atm = False):
    df = pd.read_csv(csv_file)
    df.columns = ['time (s)', 'pressure (mmHg)']

    # Adjust values
    if convert_with_atm:
        df['pressure (mmHg)'] = df['pressure (mmHg)'] - atmospheric_pressure
    
    df['time (s)'] = df['time (s)'] / freq_hz

    fig = px.line(df, x="time (s)", y="pressure (mmHg)", title='Pressure in mmHg', )
    fig.show()
    return df

In [30]:
df = plot_pressure('data/2025-11-25_18h08.csv', convert_with_atm=True)

In [9]:
plot_pressure('data/2025-11-25_17h48.csv', convert_with_atm=True)

         time (s)  pressure (mmHg)
0        0.016667           -12.26
1        0.033333           -12.20
2        0.050000           -12.17
3        0.066667           -12.21
4        0.083333           -12.18
...           ...              ...
22877  381.300000            -9.09
22878  381.316667            -9.08
22879  381.333333            -9.17
22880  381.350000            -9.10
22881  381.366667            -9.11

[22882 rows x 2 columns]

In [10]:
plot_pressure('data/0_PWM.csv')

       time (s)  pressure (mmHg)
0      0.016667            -3.08
1      0.033333            -3.07
2      0.050000            -3.07
3      0.066667            -3.07
4      0.083333            -3.07
...         ...              ...
3426  57.116667            -3.21
3427  57.133333            -3.25
3428  57.150000            -3.16
3429  57.166667            -3.13
3430  57.183333            -3.16

[3431 rows x 2 columns]

In [46]:
import plotly.graph_objects as go


def plot_multi_pressure(files, start_at_increase = False):
    dfs = []
    for f in files:
        df = pd.read_csv(f)
        df.columns = ['time (s)', 'pressure (mmHg)']

        # Adjust values
        df['time (s)'] = df['time (s)'] / freq_hz

        if start_at_increase:
            df_gt_0 = df[df['pressure (mmHg)'] > 0]['time (s)']
            if len(df_gt_0) > 0:
                time_offset = df_gt_0.iloc[0]
                df['time (s)'] = df['time (s)'] - time_offset
                df = df[df['pressure (mmHg)'] > 0]

        dfs.append(df)


    fig = go.Figure()

    for df, f in zip(dfs, files):
        fig.add_trace(go.Scatter(x=df['time (s)'], y=df['pressure (mmHg)'], mode='lines', name=f))

    fig.update_layout(title="Pressure Measured in Blood Pressure Cuff")
        
    fig.show()

In [47]:
plot_multi_pressure(['data/0_PWM.csv', 'data/100_PWM.csv', 'data/192_PWM.csv'])

In [48]:
plot_multi_pressure(['data/0_PWM.csv', 'data/100_PWM.csv', 'data/192_PWM.csv','data/stepwise_dorian.csv', 'data/stepwise_jon.csv'], start_at_increase=True)